FROM node:6.10-alpine

# Install Spoke
RUN mkdir Spoke
WORKDIR /Spoke

COPY package.json ./
RUN yarn

COPY . ./
ENV PORT 3000
ENV NODE_ENV production
RUN OUTPUT_DIR=./build npm run prod-build-server && \
    OUTPUT_DIR=./build npm run prod-build-client

EXPOSE 3000
# Spoke Runtime
CMD ["npm", "run", "start"]
